### ISSUE TITLE
Add support for server side rendering

### ISSUE THREAD

**Issue by TheBITLINK** [guithess/revuest#1]
When using SSR, the `window` object does not exist, therefore crashing the application.

A workaround would be to always use default object on the server, or an empty one.

**Comment by guithess** [comment]
I'm quite new to Vue.js and still didn't have time to check on SSR, but I'll see what I can do.

**Comment by TheBITLINK** [comment]
I'll see if i can make a PR later

**Comment by guithess** [comment]
@TheBITLINK, should work now. Can you please check on your setup before I close the issue?

**Comment by TheBITLINK** [comment]
Nice! it works perfectly.
